function tmp=subFigureMat4D( PLR_ave_4D, Delay_4D, energy_per_bit_4D, bandwidth_uti_4D, throughput_4D, show_dim_ind, dim_num, xlabel_str)
%% 显示四维中的某一维对系统性能的影响
% %         figure
% %         subplot(321)
% %         bar(myRA_PLR_ave'*100)
% %         xlabel('Algorithm index')
% %         ylabel('Average PLR (%)')l
% %         title('Average PLR')
% %        % legend('proposed algorithm','optimal offline ','online','fixed')
% %         subplot(322)
% %         bar(myRA_Delay')
% %         xlabel('Algorithm index')
% %         ylabel('Average Delay (ms)')
% %         title('Average Delay')
% %         %legend('proposed algorithm','optimal offline ','online','fixed')
% %         subplot(323)
% %         bar(myRA_energy_per_bit')
% %         xlabel('Algorithm index')
% %         ylabel('Average energy per bit (uJ/bit)')
% %         title('Average energy per bit')
% %         %legend('proposed algorithm','optimal offline ','online','fixed')
% %         subplot(324)
% %         bar(myRA_bandwidth_uti'*100)
% %         xlabel('Algorithm index')
% %         ylabel('Bandwidth utilization ratio')
% %         title('Bandwidth utilization ratio')
% %         %legend('proposed algorithm','optimal offline ','online','fixed')
% %         subplot(325)
% %         bar(myRA_throughput')
% %         xlabel('Algorithm index')
% %         ylabel('Average throughput')
% %         title('Average throughput')
% %         %legend('proposed algorithm','optimal offline ','online','fixed')
end
